// This file is automatically generated.
// Please do not change this file!
export const c: string;
export const db: string;
export const ellipsis: string;
export const l: string;
export const lil: string;
export const m: string;
export const none: string;
export const oa: string;
export const oh: string;
export const pa: string;
export const pr: string;
export const px: string;
export const r: string;
