// This file is automatically generated.
// Please do not change this file!
export const colors: string;
export const dark: string;
export const hw: string;
export const hw_p: string;
export const pt18: string;
